version: "3.7"

services:
  database:
    image: postgres:15-alpine
    container_name: hospital_db
    environment:
      POSTGRES_DB:       hospital_schedule
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: "@Justin2020"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres -d hospital_schedule"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks: [hospital_net]

  backend:
    build: ./backend
    container_name: hospital_backend
    environment:
      NODE_ENV: production
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: hospital_schedule
      DB_USER: postgres
      DB_PASSWORD: "@Justin2020"
      JWT_SECRET: "hDk7S9mLpQ2xR5vT8nY3zX6cB1aE4gF0jW3pL7dK9sM"
      PORT: 5000
    ports: ["5000:5000"]
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    networks: [hospital_net]

  frontend:
    build: .
    container_name: hospital_frontend
    ports: ["80:80"]
    environment:
      VITE_API_URL: http://localhost:5000
    depends_on: [backend]
    restart: unless-stopped
    networks: [hospital_net]

volumes:
  postgres_data:

networks:
  hospital_net:
    driver: bridge
