services:
  - type: web
    name: hospital-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /health
  - type: web
    name: hospital-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishPath: dist
    plan: free
    envVars:
      - key: VITE_API_URL
        sync: false
