app = "hospital-backend-chinw"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

# Optional HTTP health check if you want tighter config
#[checks]
#  [checks.api]
#    type = "http"
#    interval = "15s"
#    timeout = "2s"
#    grace_period = "10s"
#    method = "get"
#    path = "/health"
